name: donate2
recipe: laravel
config:
  php: '8.1'
  composer_version: '2.4.1'
  via: nginx
  webroot: public
  database: mysql:5.7
  cache: none
  xdebug: true
services:
  node:
    type: node:22
tooling:
  npm:
    service: node
env_file:
  - .env.lando